veeresh9148/angulerproject
AngularLearners/Angularproject pull request #6
Opened 2022-11-08 14:26 UTC by veeresh9148

Changes by Veeresh

2022-11-09 11:14 UTC, itssinghashish requested changes
Please change the input id's

2022-11-09 11:14 UTC, itssinghashish commented on Veeresh/HTML5/Assignment1.html
> +           <input type="text" name="name" id="text" placeholder="Enter Your Name" autocomplete="off"><br><br>
Please give proper id's. some meaningful id. Also check the same for other id's

2022-11-10 07:06 UTC, itssinghashish commented on Veeresh/HTML5/Assignment1.html
> +            <input type="text" name="name" id="name" placeholder="Enter Your Name" autocomplete="off"><br><br>
change as inp_name

2022-11-10 07:07 UTC, itssinghashish requested changes
please check my inline comments

2022-11-10 07:07 UTC, itssinghashish commented on Veeresh/HTML5/Assignment1.html
> +            <input type="email" name="name" id="email" placeholder="Enter Your Email" autocomplete="off"><br><br>
change as inp_email. Similarly change for others. Try to standardize the naming convention.

2022-11-10 11:58 UTC, itssinghashish reviewed
looks good hence approving

2022-11-11 03:40 UTC, rajukt15 approved these changes

2022-11-11 06:14 UTC, itssinghashish approved these changes

2022-11-11 06:14 UTC, merged